# Generated by Django 2.2 on 2019-04-30 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_auto_20190430_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='contents',
            field=models.TextField(blank=True),
        ),
    ]
